/* GENERADO por scripts/icons.mjs — no editar a mano.

   Los tags de cada icono, para el buscador de la galería del kit. Va aparte de
   icons.gen.ts a propósito: si los tags viajaran con los codepoints, la app de
   producto pagaría en su bundle el catálogo de búsqueda del muestrario. Esto lo
   importa SOLO la historia del kit. */
import type { IconName } from './icons.gen'

export const iconTags: Record<IconName, string> = {
  accessibility: "access accessible aid assistance barrier-free body disability disabled",
  add: "+ addition append arithmetic attach combine create cross",
  adjust: "alter auto click bar bars calibration center change circle",
  alarm: "access adjust alert appointment bell calendar circle clock",
  analytics: "analysis assessment bar bar chart bars business chart dashboard",
  api: "access application backend bridge cloud code coding communication",
  apps: "3x3 grid access all all apps application applications circles collection",
  arrow_back: "disable_ios app application back button backward chevron components direction",
  arrow_downward: "app application collapse components continue descending direction down",
  arrow_forward: "advance app application arrows button components continue control",
  arrow_upward: "above app application ascend components direction elevate expand",
  article: "blog content description doc document documentation editorial feed",
  attach_file: "add append attachment binding chain choose clip communication",
  badge: "accolade account achievement approval avatar award card certificate",
  bar_chart: "analysis analytics bar chart bars business columns dashboard data",
  bolt: "alert charge current danger electric electricity energy fast",
  bookmark: "app archive article book browser collection content corner",
  bookmarks: "bookmark browser collection document favorite favorites file flag",
  build: "adjust adjustment building configuration construction control engineering equipment",
  calculate: "+ - = addition arithmetic calculator count counting",
  calendar_month: "agenda appointment button clock date day duration element",
  campaign: "achievement action advertisement alert announcement banner celebration concept",
  cancel: "abort action block button circle clear close cross",
  chat: "alert bubble comment communicate communication connect contact conversation",
  check: "! disable_ios acceptance achievement alert apply approve attention",
  check_circle: "accept approval approve checkmark complete completion confirm confirmation",
  chevron_left: "disable_ios angle arrow arrows back backward before caret",
  chevron_right: "advance angle arrow arrows bracket caret carousel continue",
  close: "abort action alert cancel cancel button clear confirmation cross",
  close_fullscreen: "action arrow arrows arrows inward box button collapse contract",
  cloud: "air atmosphere climate cloudy connection environment filled forecast",
  cloud_download: "access app application arrow backup cloud computing cloud storage computer",
  cloud_upload: "app application arrow backup computing connection data digital",
  code: "algorithm application backend brackets build coding commands compile",
  content_copy: "action clipboard clone copy content create cut data doc",
  content_cut: "action audio blade clip copy craft divide doc",
  content_paste: "action add application attach button clip clipboard control",
  create_new_folder: "+ add addition archive build collection content data",
  credit_card: "account account information amex balance bank banking bill buy",
  dark_mode: "accessibility ambient app appearance application atmosphere bedtime circle",
  dashboard: "add administration analytics cards chart circle control data",
  database: "access analytics archive bar bars chart cloud coin",
  delete: "action basket bin can cancel clean up clear control",
  deployed_code: "3d algorithm angle bracket application bracket build coding command",
  description: "article content data details doc document draft drive",
  download: "acquire action app application archive arrow bar button",
  draft: "attachment blank data doc document dog-ear drive editor",
  drag_indicator: "action app application circles column components control design",
  edit: "action alter author change compose control create document",
  error: "! alert attention bug caution circle critical danger",
  event: "add add event add invitation add to calendar agenda appointment booking calendar",
  expand_content: "adjustment area arrow arrows bigger chevron collapse data",
  explore: "adventure browse compass curiosity destination direction discover discovery",
  extension: "addon app browser-extension compatibility component connect connection extended",
  favorite: "affection appreciate appreciation bookmark border button collection data",
  filter_alt: "adjust arrange choose control customize data edit find",
  filter_list: "arrange bar bar graph bars categorize control criteria filtering",
  folder: "administration archive browse business category collection computer container",
  folder_open: "access archive browse collection computer container content data",
  forum: "answers bubble chat comment comments communicate communication communication bubble",
  fullscreen: "adjust app application aspect ratio big cinema mode components display",
  functions: "adjustments administration algorithms automation average calculate capabilities cogwheels",
  grid_view: "app application square arrangement block layout blocks boxes components content",
  group: "accounts administration audience basic committee community contacts crowd",
  group_add: "accounts add friend add member add user avatar circle collaborate collective",
  handyman: "adjust build builder cog configuration construction craftsman customize",
  help: "? about answer assistance button circle circular documentation",
  history: "activity arrow back backup backwards circular clear clock",
  home: "abode address app application--house architecture beginning building button",
  image: "add adjust album asset camera collection crop display",
  inbox: "archive arrival box category communication container correspondence email",
  info: "about alert announcement assistance circle content data details",
  inventory_2: "archive assets box boxes collection container count crate",
  keyboard_arrow_down: "access arrows bottom caret chevron collapse control direction",
  keyboard_arrow_up: "accordion angle arrows ascend caret chevron collapse control",
  label: "angled shape badge bookmark category classification corner designation detail",
  language: "announcement bubble caption chat communicate communication dialogue discussion",
  layers: "arrange composition content depth disabled display document enabled",
  light_mode: "adjustment appearance application bright brightness celestial body circle clear",
  lightbulb: "alert announcement bright bulb concept creativity disabled education",
  link: "anchor arrow attach attachment chain circle circular clip",
  location_on: "address area current location destination direction drop find geography",
  lock: "access authentication authorization browser closed confidential connection data",
  lock_open: "access action open authorized button open control open freedom grant access keyhole",
  logout: "access account app application arrow arrow pointing right arrow right authentication",
  mail: "communication contact correspondence diagonal lines digital electronic mail email empty",
  manage_accounts: "access administration avatar bust change circle control customization",
  map: "address atlas cartography city continent country destination direction",
  menu: "action menu app app menu application application menu bars burger collapse",
  menu_book: "catalog dictionary dining directory documentation education food glossary",
  mic: "audio audio button audio capture audio input audio recording chat communication dictate",
  more_horiz: "3 disable_ios actions additional app application bar menu button",
  more_vert: "3 disable_ios actions additional options android app application components",
  note_add: "+ add document add note create create document data doc document",
  notifications: "active alarm alert announcement app bell chime communication",
  open_in_new: "access action app application arrow box button components",
  palette: "appearance art artist artistic brush color colors creative",
  pause: "action audio break button command control controls function",
  payments: "bank banking bill bills buy card cash coin",
  person: "account avatar avatar filled avatar outline body circle contact face",
  person_add: "+ account account outline add contact add friend add person add user avatar",
  pie_chart: "analysis analytics bar bars business circle comparison data",
  play_arrow: "app application audio back begin button cinema components",
  print: "copier copy device document draft fax hardware ink",
  psychology: "awareness behavior body brain brainstorm clever cognitive concept",
  public: "access accessibility circle community connection country earth everybody",
  receipt_long: "accounting bill business check checkout details document expense",
  redo: "action advancement again arrow backward clockwise command control",
  refresh: "application around arrow arrows browser circular content current",
  rocket_launch: "accelerate ascent astronaut boost cosmic exploration fast flight",
  save: "action backup button computer control data disk document",
  schedule: "alarm appointment calendar chronometer clock countdown date deadline",
  school: "academic academics academy achievement architecture building building facade campus",
  science: "analysis beaker chemical chemistry container discovery education experiment",
  search: "browse circle discover explore filter find glass handle",
  search_off: "access denied blocked blocked access cancel cancel search circle clear clear search",
  sell: "bargain bill card cart cash coin commerce coupon",
  send: "action airplane arrow chat communication complete data deliver",
  settings: "adjustments administration administration panel application change cog cogwheel configuration",
  share: "disable_ios activity andriod share android arrow communication connect connection",
  skip_next: "advance arrow audio player bar button control controls fast forward",
  skip_previous: "arrow audio back bar beginning button control controls",
  smart_toy: "ai android artificial intelligence assistant automation bot character chatbot",
  sort: "alphabetize arrange arrow ascending categorize change order content data",
  star: "add to favorite best bookmark border empty empty star favorite five pointed star",
  star_shine: "achievement ai artificial intelligence astral automation bookmark bright celestial",
  stars_2: "achievement ai artificial intelligence astronomy automation award bookmark celestial",
  stop: "action audio basic block button close command control",
  support_agent: "advisor answer assistance avatar bubble call care chat",
  swap_vert: "arrow arrows bidirectional connection data direction direction change document",
  sync: "360 align around arrow arrows circular cloud connection",
  tab: "add button add document add tab add window application management application window browser browser control",
  table_rows: "array background chart data database document entries file",
  terminal: "it administration angle brackets application code coding command line command prompt",
  thumb_up: "acknowledgement agree approve button choice confirmation content interaction control",
  timer: "alarm alert appointment bell chronometer circular clock countdown",
  today: "agenda appointment calendar circle circle with dot clock contemporary current",
  translate: "arrow bidirectional bubble change chat communication conversion dictionary",
  trending_up: "analysis analytics arrow ascending business chart data diagram",
  tune: "adjust adjustments audio balance bars bass configure control",
  undo: "action arrow back backward cancel change command correction",
  upload: "add arrow arrows attach backup cloud data direction",
  verified_user: "approve badge certified check complete confirmation data done",
  view_column: "alignment arrangement columns data data display design display divide",
  view_list: "arrangement bulleted catalog compact content data design directory",
  visibility: "display eye glance hidden hidden text insight look observe",
  visibility_off: "conceal crossed out eye diagonal line disabled disabled view enabled eye form",
  volume_off: "accessibility audio audio control audio off control cross out diagonal line disabled",
  volume_up: "acoustic adjust volume amplify audio audio bars audio control audio output control",
  wand_stars: "abstract action ai apply artificial intelligence asterisk automation create",
  warning: "! alert app attention caution danger error exclamation",
  widgets: "add app arrange blocks box boxes components customize",
  workspace_premium: "achievement approval authentic authority award badge certification circle",
  zoom_in: "action add big bigger button circle command control",
  zoom_out: "action adjust button control decrease decrease size discover document view",
}
